### ISSUE TITLE
nhentai downloader

### ISSUE THREAD

**Issue by jennon** [baivong/Userscript#13]
Clicking "Download" ends up with a torrent file. Tried restarting browsers (Firefox 53.0.3 and Chrome  58.0.3029.110), still the same result.

**Comment by baivong** [comment]
This is a bug, if it works:
* You do not need to login.
* Download button has a blue background.

**Comment by baivong** [comment]
Please upgrade to [version 1.3.3](https://openuserjs.org/scripts/baivong/nHentai_Downloader)
