### ISSUE TITLE
Not working after chrome updated to v61.0.3163.79

### ISSUE THREAD

**Issue by mo-han** [baivong/Userscript#15]
The "Download" buttom became the original dark-gray, although Tampermonkey shows the user script is enabled.

Maybe it's not the script issue, but I didn't run into this case before updating my Chrome.

**Comment by baivong** [comment]
What is script name? This repository is a collection of scripts.

**Comment by mo-han** [comment]
My bad... It was the `nHentai_downloader`.

**Comment by baivong** [comment]
Do you get bugs at all or just some comics?
- If that's all, try these steps:
  - Disable other extensions.
  - Disable other scripts.
  - Clean cache.
  - Reinstall it.
- If only some, send problem links to my email: Zzbaivong@gmail.com

If Tampermonkey on Google Chrome isn't working, try [Violentmonkey](https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag).
Or try with [Firefox browser](https://www.mozilla.org/firefox/), use [Greasemonkey](https://addons.mozilla.org/vi/firefox/addon/greasemonkey/).
*... all of them worked for me.*

**Comment by mo-han** [comment]
After retrying for sometime I finally found the key: the external dependency [https://greasyfork.org/scripts/19855-jszip/code/jszip.js?version=164038] which `required` by `nHentai_downloader` is the boss since it has a "huge" size of 364.72 KB that really takes quite a long time to load for the first time. Once this external .js file is cached the loading will be fast but the first loading hung and made me think the script is dead.

**Comment by baivong** [comment]
Greasy Fork just crashed the server a few days ago, maybe it's time you updated this script.
