### ISSUE TITLE
Tải truyện từ TruyenCV không mở được hết

### ISSUE THREAD

**Issue by gianghd** [baivong/Userscript#17]
Khi tải thì báo tải hết nhưng khi export ra epub thì dung lượng còn có hơn 1Mb.
Mở lên thì xem đc hơn chục page. còn lại không xem được tiếp.
Mình dùng Chrome vs Tampermonkey.
Firefox vs GreaseMonkey cũng bị

Nhờ bạn xem giúp
Thanks

**Comment by baivong** [comment]
Hơn 1Mb thì khoảng 200 chương, mình vừa tải một truyện 50 chương không lỗi. Đang tải thử truyện 2000 chương.

Truyện bạn xem có **Chương VIP** không?
Bạn xem ở trang cuối của epub, phần **Ghi chú** có báo lỗi chương không?
Thử đổi đuôi **.epub** thành **.zip** rồi giải nén. Trong thư mục **EPUB**, xem mã nguồn file **content.xhtml** có đủ nội dung không?

Truyện nào cũng bị lỗi vậy hay chỉ truyện dài thôi? Nếu do truyện thì cho mình xin link truyện bị lỗi.
Ngoài ra cho mình thêm thông tin phần mềm bạn đọc truyện? Hệ điều hành?

**Comment by gianghd** [comment]
Mình không thấy VIP.
Mấy hôm trước mình tải hơn 1000 chương ko sao. Nhưng từ t6 tuần trc thì ko hiển thị được hết.
Mình tải "Ta là thổ hào ta sợ ai 2" thì dung lượng 1.4Mb.
Dùng FBReader, Win7 32bit đọc thì đc đến page 13 là ko xem tiếp được.
Dùng Extension của Chrome cũng không xem được.

Nãy tải Nghịch Thiên Thăng Cấp. Hiện tại web có hơn 500 chương nhưng lastest chỉ có 413 chương.
Đuôi không lỗi gì.

**Comment by baivong** [comment]
Không biết là họ bị hack hay cố tình, mà chèn một chuỗi ngẫu nhiên, vào vị trí ngẫu nhiên trong chương truyện. Nếu nó vô tình nằm trong tag html sẽ làm lỗi cú pháp **xhtml**. Ngoài ra họ còn chèn những ký tự đặc biệt để gây ra lỗi **PCDATA invalid Char**.
Vì chuẩn **xhtml** yêu cầu cú pháp rất nghiêm ngặt nên truyện không đọc tiếp sau điểm bị lỗi được.

Họ làm như vậy sẽ khiến văn bản bị sạn vì chuỗi ngẫu nhiên đó. Do nội dung thay đổi ngẫu nhiên nên nó cũng sẽ không cache được. Rõ là lợi bất cập hại.

Mình đang tìm danh sách ký tự gây ra lỗi **PCDATA invalid Char**, ví dụ trong truyencv có `` và ``, bạn có thông tin gì về nó không.

**Comment by baivong** [comment]
Đã tìm ra giải pháp `[^\x09\x0A\x0D\x20-\uD7FF\uE000-\uFFFD\u10000-\u10FFFF]` [?](https://stackoverflow.com/a/14323524)

**Comment by gianghd** [comment]
Có thể đấy là do tool convert của họ + thao tác khi convert làm lỗi font.
Khi convert từ tiếng trung sang, Có những ký tự tool không convert được thì Converter bằng cách nào đấy làm lỗi font. Dẫn đến lỗi ký tự.

Văn bản đang bị thì mình có thấy. Thỉnh thoảng thấy các chuỗi như kiểu 9xk32o (random ký tự) hiển thị lên. Nhìn rất buồn cười.

Bạn cho mình xin tên truyện, tên chương mà có ký tự ko hợp lệ với.

**Comment by gianghd** [comment]
Về replace ký tự thì ko biết có được ko, bạn thử làm theo giải pháp này xem.
Các mã ký tự hợp lệ thì sẽ nằm trong khoảng nào đó (unicode, ....)
ngoài khoảng hợp lệ thì sẽ remove đi.
chứ lọc từng ký tự ra rồi remove thì ko ổn lắm

**Comment by baivong** [comment]
> Bạn cho mình xin tên truyện, tên chương mà có ký tự ko hợp lệ với.

http://truyencv.com/vo-dich-kiem-vuc/chuong-338/
Nó là ký tự sau câu này: `đều là nhất kiện khảo nghiệm lòng ngưổi`

Mình đã tìm được mã regexp để lọc mấy ký tự đó rồi.
```javascript
/[^\x09\x0A\x0D\x20-\uD7FF\uE000-\uFFFD\u10000-\u10FFFF]+/
```
Còn mấy chuỗi ngẫu nhiên thì chưa tìm ra phương pháp tối ưu, vì nó gồm chữ và số, từ 6-8 ký tự. Mà trong khoảng này thì dễ trùng với vài từ Tiếng Việt dài hoặc Tiếng Anh.
```javascript
\s[a-zA-Z0-9]{6,8}(="")?\s
```

**Comment by baivong** [comment]
Các thư viện trong script này mình lưu trên [Greasy Fork](https://greasyfork.org/), mà có vẻ là nó lại sập rồi. Bạn cập nhật [v2.1.2](https://openuserjs.org/scripts/baivong/TruyenCV_downloader) nhé.
