### ISSUE TITLE
Needs update for Firefox 57 (Greasemonkey >= 4.0)

### ISSUE THREAD

**Issue by janfett** [baivong/Userscript#20]
Firefox version 57 breaks the old extensions API. Extensions like GreaseMonkey are being rewritten with the new webextensions API.

As a result of the changes, parts of the script  need to be rewritten to reflect changes. Instructions for developers are given here - https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html

At the time of writing, this userscript does not work with FF 57 with Greasemonkey 4.0 from the addons store.

**Comment by Sentricit** [comment]
Please rewrite your nHentai download script^^ You make a wonderful work.
