### ISSUE TITLE
file Ebook bị nhảy vào 1 khúc

### ISSUE THREAD

**Issue by hianalyst** [baivong/Userscript#21]
Chào bác,
Em dùng script này của bác để tải truyện con đường đế vương trên truyenfull nhưng khi đưa lên đt thì file ebook nhảy vào hẳn 1 nửa giống như hình - https://imgur.com/a/EZ71E luôn, bác chỉ em cách fix không ạ ?
Với cả bác cho thêm tùy chọn bên bachngocsach/reader được không ạ ? Bên đó có mấy bộ truyện mà bên truyenfull không có :D

**Comment by baivong** [comment]
Bạn đọc truyện bằng app gì thế, thử tìm cách vô hiệu hóa css của epub xem.

**Comment by hianalyst** [comment]
em xài fbreader bác ạ, nhưng mà em tắt css cái là dc rồi, cảm ơn bác nhiều nhé, script ngon & chất lắm ạ <3

**Comment by baivong** [comment]
Phiên bản mới của Firefox trên Android đã hỗ trợ Add-on Tampermonkey rồi đó, bạn có thể tải bằng điện thoại cũng được.

**Comment by baivong** [comment]
Tạm thời thì mình chưa có thời gian làm script cho bachngocsach, với lại mình cũng có ý định viết lại công cụ tạo epub riêng. Bạn có thể thử [Tool LeechText một số web truyện](http://banlong.us/threads/tool-leechtext-cua-mot-so-web-truyen.12471/).

**Comment by baivong** [comment]
Android thì app [AlReader](https://play.google.com/store/apps/details?id=com.neverland.alreader&hl=vi) đọc tốt hơn Fbreader, giao diện hơi xấu tí, nhưng chịu khó chỉnh màu tí là ổn.

**Comment by hianalyst** [comment]
vậy khi nào bác viết xong cái công cụ cho em xin với nhé.
em vừa cài thử cái ALreader, có vẻ dễ dùng hơn cái fb cảm ơn bác nhiều lắm <3

**Comment by baivong** [comment]
Ý mình là thư viện dùng tạo epub ấy, hiện tại mình đang dùng [js-epub-maker](https://github.com/bbottema/js-epub-maker). Thư viện này khá ổn, nhưng nó không tương thích với các trình đọc epub cũ, hơn nữa nó gom tất cả chương truyện vào một file nên sẽ khi gặp truyện dài thì trình đọc epub mở khá chậm.

**Comment by hianalyst** [comment]
vâng :D
em chờ phiên bản mới của bác,
một lần nữa cảm ơn bác nhé, chúc bác buổi tối vui vẻ

**Comment by baivong** [comment]
Không có chi, mình cũng chúc bạn buổi tối vui vẻ nhé 🤗
