### ISSUE TITLE
Bị chặn khi tải truyện (script download truyenyy)

### ISSUE THREAD

**Issue by vhchung** [baivong/Userscript#4]
Tốc độ tải các chương nhanh nhưng không có cơ chế thay đổi IP, proxy hay user agent gì nên cứ tải được 20 chương thì lại bị chặn và phải chờ để tiếp tục. Bạn có thể khắc phục được vấn đề này không?

**Comment by baivong** [comment]
Mình biết lỗi này nhưng IP không dễ kiếm, mà có kiếm cũng không dùng trong Userscript được. Lúc viết xong script này mình tải 2 truyện, đến giờ đọc vẫn chưa xong. Nếu chỉ dùng script cho mục đích cá nhân thì vẫn chấp nhận được.
Hoặc, tìm một web truyện nào khác, tương đương, không bị chặn, mình sẽ dành thời gian viết script để tải truyện trên đó.

**Comment by vhchung** [comment]
Dù sao cũng cảm ơn script của bạn. Script như thế này rất thú vị và tiện lợi 👍
