### ISSUE TITLE
make popup blocker works only on specific website

### ISSUE THREAD

**Issue by ale82to** [baivong/Userscript#6]
is it possible to make popupblocker works only on specific website? ,it causes tons of problem for me if i enable it for every web site ,for example a stupid bookmarklet to duplicate a webpage wont work with popup blocker enabled.
i tried changing //match http*
with both // @include (wanted website) and //match(wanted website with no luck)
thanks

**Comment by baivong** [comment]
### Please provide more details:
1. The URL of websites that make Popup Blocker do not work..
2. Your Operating System. (Eg: Windows 10)
3. Your browser's name and version. (Eg: Google Chrome 51)
4. Userscript management that you are using. (Eg: Tampermonkey 4)

### About block and allow in this script:
* Popup blocker work with all websites [L9-L10](https://github.com/baivong/Userscript/blob/639af23963ce69b4a0ccca3581bd07f023d3ffd2/popup_blocker/popup_blocker.user.js#L9-L10)
* [L18](https://github.com/baivong/Userscript/blob/639af23963ce69b4a0ccca3581bd07f023d3ffd2/popup_blocker/popup_blocker.user.js#L18) is a list of websites allow popup. If you want a website to allow all popup, let add its domain in this line, or use `@exclude` metadata.
* [L100](https://github.com/baivong/Userscript/blob/639af23963ce69b4a0ccca3581bd07f023d3ffd2/popup_blocker/popup_blocker.user.js#L100) + [L117](https://github.com/baivong/Userscript/blob/639af23963ce69b4a0ccca3581bd07f023d3ffd2/popup_blocker/popup_blocker.user.js#L117) will ignore all internal links.
* [L135-L138](https://github.com/baivong/Userscript/blob/639af23963ce69b4a0ccca3581bd07f023d3ffd2/popup_blocker/popup_blocker.user.js#L135-L138) will ignore forums use [Discourse](https://github.com/discourse/discourse).

**Comment by baivong** [comment]
I'm sorry, the previous answer (deleted), I did misunderstand you.
If you use a specific `@match` metadata, the script will run in a sandbox. That makes it impossible to access `window` object, and inactivity.
Here is the version for you. Please edit `block` parameter _(line 18)_, and add to the list of domains you want to Popup Blocker works, separated by vertical bars `|` _(Ctrl+\\)_.

```javascript
// ==UserScript==
// @name         popup blocker
// @namespace    http://baivong.github.io/
// @description  Block all javascript popup and link has click event. Double click to open link blocked.
// @version      1.3.0-custom
// @icon         http://i.imgur.com/yUHcAyG.png
// @author       Zzbaivong
// @license      MIT
// @match        http://*/*
// @match        https://*/*
// @supportURL   https://github.com/baivong/Userscript/issues
// @run-at       document-start
// @grant        none
// ==/UserScript==


var popupBlockerConfigs = {
    block: 'fiddle.jshell.net|jsfiddle.net', // Domain
    popup: false, // true|false
    click: false // true|false
};



(function (global) {
    'use strict';

    global.Element.prototype._addEventListener = global.Element.prototype.addEventListener;
    global.Element.prototype.addEventListener = function (a, b, c) {
        this._addEventListener(a, b, c);
        if (!this.eventListenerList) this.eventListenerList = {};
        if (!this.eventListenerList[a]) this.eventListenerList[a] = [];
        this.eventListenerList[a].push(b);
    };

    var popupBlocker = {};
    popupBlocker.userscript = {
        block: popupBlockerConfigs.block.split('|'),
        host: global.location.host,
        blockSite: false,
        testHost: function (hostMatch, hostTest) {
            var matchHost = new RegExp('^([\\w\\.\\-]+\\.)?' + hostMatch.replace(/\./g, '\\.') + '$');
            return matchHost.test(hostTest);
        },
        checkSite: function () {
            var list = this.block,
                listSize = list.length;

            if (!listSize) return;

            for (var i = 0; i < listSize; i++) {
                if (!this.testHost(list[i], this.host)) {
                    this.blockSite = true;
                    break;
                }
            }

            return this.blockSite;
        },
        logs: function (str) {
            if (global.console) global.console.log(str, this.host);
        },
        counter: 0,
        warns: function (str) {
            if (global.console) global.console.warn(this.counter, 'popups blocked\n' + str);
        },
        init: function () {
            var blocker = this,
                allLinks = document.getElementsByTagName('a'),
                allLinksSize = allLinks.length,
                hanler = function (event) {
                    event.preventDefault();
                    var _this = (this === document) ? event.target : this;

                    blocker.counter++;
                    blocker.warns(_this.href + '\n' + _this.target + '\nClick');
                },
                dbhanler = function (event) {
                    event.preventDefault();
                    var _this = (this === document) ? event.target : this;

                    global._open(_this.href, '_blank');
                };

            if (!allLinksSize) return;

            if (typeof global.jQuery !== 'undefined') {
                $(function () {
                    var $ = global.jQuery,
                        $doc = $(document),
                        $event = $doc.data('events') || $._data(document, 'events');

                    if (!$doc.data('popupblocker') && $event && $event.click) $.each($event.click, function () {
                        var _this = this.selector;

                        if (_this) $(_this).each(function (i, ele) {
                            var $this = $(ele),
                                dataSelector;
                            if ($this[0].tagName !== 'A') return;
                            if (blocker.testHost(blocker.host, ele.host)) return;

                            $this.attr('data-selector', 'popupblocker' + i);
                            dataSelector = 'a[data-selector="popupblocker' + i + '"]';
                            if ($.fn.on) {
                                $doc.on('click', dataSelector, hanler).on('dblclick', dataSelector, dbhanler).data('popupblocker', true);
                            } else {
                                $(dataSelector).live('click', hanler).live('dblclick', dbhanler).attr('data-popupblocker', true);
                            }
                        });
                    });
                });
            }

            for (var i = 0; i < allLinksSize; i++) {
                var link = allLinks[i];

                if (!this.testHost(this.host, link.host) && !link.dataset.popupblocker && (link.onclick || (link.eventListenerList && link.eventListenerList.click))) {
                    link.addEventListener('click', hanler, false);
                    link.addEventListener('dblclick', dbhanler, false);
                }

                link.dataset.popupblocker = true;
            }
        }
    };

    if (popupBlocker.userscript.checkSite()) {
        popupBlocker.userscript.logs('Popup blocker is disabled.');
        return;
    } else {
        popupBlocker.userscript.logs('Popup blocker is running.');
    }

    document.addEventListener('DOMContentLoaded', function () {
        if (('Discourse' in global)) {
            popupBlocker.userscript.logs('Popup blocker is disabled on Discourse.');
            return;
        }

        global._open = global.open;

        if (!popupBlockerConfigs.popup) global.open = function (url, target, params) {
            popupBlocker.userscript.counter++;
            popupBlocker.userscript.warns(url + '\n' + target + '\n' + params);
            return false;
        };

        if (popupBlockerConfigs.click) return;
        var oldXHR = global.XMLHttpRequest;

        function newXHR() {
            var realXHR = new oldXHR();
            realXHR.addEventListener('readystatechange', function () {
                popupBlocker.userscript.init();
            }, false);
            return realXHR;
        }
        global.XMLHttpRequest = newXHR;

        popupBlocker.userscript.init();

    });

})(window);
```

**Comment by ale82to** [comment]
thankyou for the reply but that did not work if i want to block popup only on 
altadefinizone.site 

i tried this code 
// ==UserScript==
// @name         popup blocker
// @namespace    http://baivong.github.io/
// @description  Block all javascript popup and link has click event. Double click to open link blocked.
// @version      1.3.0
// @icon         
// @author       Zzbaivong
// @license      MIT
// @match        http://*/*
// @match        https://*/*
// @supportURL   https://github.com/baivong/Userscript/issues
// @run-at       document-start
// @grant        none
// ==/UserScript==


var popupBlockerConfigs = {
    allow: 'google.com|google.com.vn|facebook.com|twitter.com|github.com|youtube.com|imgur.com|messenger.com|openuserjs.org|greasyfork.org|worldcosplay.net', // Domain
    popup: false, // true|false
    click: false // true|false
};



(function (global) {
    'use strict';

    global.Element.prototype._addEventListener = global.Element.prototype.addEventListener;
    global.Element.prototype.addEventListener = function (a, b, c) {
        this._addEventListener(a, b, c);
        if (!this.eventListenerList) this.eventListenerList = {};
        if (!this.eventListenerList[a]) this.eventListenerList[a] = [];
        this.eventListenerList[a].push(b);
    };

    var popupBlocker = {};
    popupBlocker.userscript = {
        allow: popupBlockerConfigs.allow.split('|'),
        host: global.location.host,
        allowSite: false,
        testHost: function (hostMatch, hostTest) {
            var matchHost = new RegExp('^([\\w\\.\\-]+\\.)?' + hostMatch.replace(/\./g, '\\.') + '$');
            return matchHost.test(hostTest);
        },
        checkSite: function () {
            var list = this.allow,
                listSize = list.length;

            if (!listSize) return;

            for (var i = 0; i < listSize; i++) {
                if (this.testHost(list[i], this.host)) {
                    this.allowSite = true;
                    break;
                }
            }

            return this.allowSite;
        },
        logs: function (str) {
            if (global.console) global.console.log(str, this.host);
        },
        counter: 0,
        warns: function (str) {
            if (global.console) global.console.warn(this.counter, 'popups blocked\n' + str);
        },
        init: function () {
            var blocker = this,
                allLinks = document.getElementsByTagName('a'),
                allLinksSize = allLinks.length,
                hanler = function (event) {
                    event.preventDefault();
                    var _this = (this === document) ? event.target : this;

                    blocker.counter++;
                    blocker.warns(_this.href + '\n' + _this.target + '\nClick');
                },
                dbhanler = function (event) {
                    event.preventDefault();
                    var _this = (this === document) ? event.target : this;

                    global._open(_this.href, '_blank');
                };

            if (!allLinksSize) return;

            if (typeof global.jQuery !== 'undefined') {
                $(function () {
                    var $ = global.jQuery,
                        $doc = $(document),
                        $event = $doc.data('events') || $._data(document, 'events');

                    if (!$doc.data('popupblocker') && $event && $event.click) $.each($event.click, function () {
                        var _this = this.selector;

                        if (_this) $(_this).each(function (i, ele) {
                            var $this = $(ele),
                                dataSelector;
                            if ($this[0].tagName !== 'A') return;
                            if (blocker.testHost(blocker.host, ele.host)) return;

                            $this.attr('data-selector', 'popupblocker' + i);
                            dataSelector = 'a[data-selector="popupblocker' + i + '"]';
                            if ($.fn.on) {
                                $doc.on('click', dataSelector, hanler).on('dblclick', dataSelector, dbhanler).data('popupblocker', true);
                            } else {
                                $(dataSelector).live('click', hanler).live('dblclick', dbhanler).attr('data-popupblocker', true);
                            }
                        });
                    });
                });
            }

            for (var i = 0; i < allLinksSize; i++) {
                var link = allLinks[i];

                if (!this.testHost(this.host, link.host) && !link.dataset.popupblocker && (link.onclick || (link.eventListenerList && link.eventListenerList.click))) {
                    link.addEventListener('click', hanler, false);
                    link.addEventListener('dblclick', dbhanler, false);
                }

                link.dataset.popupblocker = true;
            }
        }
    };

    if (popupBlocker.userscript.checkSite()) {
        popupBlocker.userscript.logs('Popup blocker is disabled.');
        return;
    } else {
        popupBlocker.userscript.logs('Popup blocker is running.');
    }

    document.addEventListener('DOMContentLoaded', function () {
        if (('Discourse' in global)) {
            popupBlocker.userscript.logs('Popup blocker is disabled on Discourse.');
            return;
        }

        global._open = global.open;

        if (!popupBlockerConfigs.popup) global.open = function (url, target, params) {
            popupBlocker.userscript.counter++;
            popupBlocker.userscript.warns(url + '\n' + target + '\n' + params);
            return false;
        };

        if (popupBlockerConfigs.click) return;
        var oldXHR = global.XMLHttpRequest;

        function newXHR() {
            var realXHR = new oldXHR();
            realXHR.addEventListener('readystatechange', function () {
                popupBlocker.userscript.init();
            }, false);
            return realXHR;
        }
        global.XMLHttpRequest = newXHR;

        popupBlocker.userscript.init();

    });

})(window);

but clicking on the x popup ads
ad open in new window
test this url 
http://altadefinizione.site/passo-falso/

**Comment by baivong** [comment]
Thank you for reporting this bug. I had to fix it for you.

```javascript
// ==UserScript==
// @name         popup blocker
// @namespace    http://baivong.github.io/
// @description  Block all javascript popup and link has click event. Double click to open link blocked.
// @version      1.3.1-reverse
// @icon         http://i.imgur.com/yUHcAyG.png
// @author       Zzbaivong
// @license      MIT
// @match        http://*/*
// @match        https://*/*
// @supportURL   https://github.com/baivong/Userscript/issues
// @run-at       document-start
// @grant        none
// ==/UserScript==


var popupBlockerConfigs = {
    block: 'hdpass.net|altadefinizione.site', // Domain
    popup: false, // true|false
    click: false // true|false
};



(function (global) {
    'use strict';

    global.Element.prototype._addEventListener = global.Element.prototype.addEventListener;
    global.Element.prototype.addEventListener = function (a, b, c) {
        this._addEventListener(a, b, c);
        if (!this.eventListenerList) this.eventListenerList = {};
        if (!this.eventListenerList[a]) this.eventListenerList[a] = [];
        this.eventListenerList[a].push(b);
    };

    var popupBlocker = {};
    popupBlocker.userscript = {
        block: popupBlockerConfigs.block.split('|'),
        host: global.self.location.host,
        blockSite: false,
        testHost: function (hostMatch, hostTest) {
            var matchHost = new RegExp('^([\\w\\.\\-]+\\.)?' + hostMatch.replace(/\./g, '\\.') + '$');
            return matchHost.test(hostTest);
        },
        checkSite: function () {
            var list = this.block,
                listSize = list.length;

            if (!listSize) return;

            for (var i = 0; i < listSize; i++) {
                if (this.testHost(list[i], this.host)) {
                    this.blockSite = true;
                }
                if(this.blockSite === true) break;
            }

            return this.blockSite;
        },
        logs: function (str) {
            if (global.console) global.console.log(str, this.host);
        },
        counter: 0,
        warns: function (str) {
            if (global.console) global.console.warn(this.counter, 'popups blocked\n' + str);
        },
        init: function () {
            var blocker = this,
                allLinks = document.getElementsByTagName('a'),
                allLinksSize = allLinks.length,
                hanler = function (event) {
                    event.preventDefault();
                    var _this = (this === document) ? event.target : this;

                    blocker.counter++;
                    blocker.warns(_this.href + '\n' + _this.target + '\nClick');
                },
                dbhanler = function (event) {
                    event.preventDefault();
                    var _this = (this === document) ? event.target : this;

                    global._open(_this.href, '_blank');
                };

            if (!allLinksSize) return;

            if (typeof global.jQuery !== 'undefined') {
                $(function () {
                    var $ = global.jQuery,
                        $doc = $(document),
                        $event = $doc.data('events') || $._data(document, 'events');

                    if (!$doc.data('popupblocker') && $event && $event.click) $.each($event.click, function () {
                        var _this = this.selector;

                        if (_this) $(_this).each(function (i, ele) {
                            var $this = $(ele),
                                dataSelector;
                            if ($this[0].tagName !== 'A') return;
                            if (blocker.testHost(blocker.host, ele.host)) return;

                            $this.attr('data-selector', 'popupblocker' + i);
                            dataSelector = 'a[data-selector="popupblocker' + i + '"]';
                            if ($.fn.on) {
                                $doc.on('click', dataSelector, hanler).on('dblclick', dataSelector, dbhanler).data('popupblocker', true);
                            } else {
                                $(dataSelector).live('click', hanler).live('dblclick', dbhanler).attr('data-popupblocker', true);
                            }
                        });
                    });
                });
            }

            for (var i = 0; i < allLinksSize; i++) {
                var link = allLinks[i];

                if (!this.testHost(this.host, link.host) && !link.dataset.popupblocker && (link.onclick || (link.eventListenerList && link.eventListenerList.click))) {
                    link.addEventListener('click', hanler, false);
                    link.addEventListener('dblclick', dbhanler, false);
                }

                link.dataset.popupblocker = true;
            }
        }
    };

    if (!popupBlocker.userscript.checkSite()) {
        popupBlocker.userscript.logs('Popup blocker is disabled.');
        return;
    } else {
        popupBlocker.userscript.logs('Popup blocker is running.');
    }

    document.addEventListener('DOMContentLoaded', function () {
        if (('Discourse' in global)) {
            popupBlocker.userscript.logs('Popup blocker is disabled on Discourse.');
            return;
        }

        global._open = global.open;

        if (!popupBlockerConfigs.popup) global.open = function (url, target, params) {
            popupBlocker.userscript.counter++;
            popupBlocker.userscript.warns(url + '\n' + target + '\n' + params);
            return false;
        };

        if (popupBlockerConfigs.click) return;
        var oldXHR = global.XMLHttpRequest;

        function newXHR() {
            var realXHR = new oldXHR();
            realXHR.addEventListener('readystatechange', function () {
                popupBlocker.userscript.init();
            }, false);
            return realXHR;
        }
        global.XMLHttpRequest = newXHR;

        popupBlocker.userscript.init();

    });

})(window);
```

![blocker](https://cloud.githubusercontent.com/assets/5460915/16754495/6a638bea-481d-11e6-8ef3-e57021acf250.png)

**Comment by ale82to** [comment]
thank you works percetly now!!

**Comment by ale82to** [comment]
sorry for bothering again which the correct syntax for the script to run only on this url http://www.fastvideo.me/94o1xpkjrl0z/Brief.Encounters.S01E01.mp4.html
i tried fastvideo.eu|adexchangeprediction.com|Fastvideo.eu
but it doesn work 
thanks
