### ISSUE TITLE
Anti social locker

### ISSUE THREAD

**Issue by nntoan** [baivong/Userscript#8]
Hi @baivong,

I'm wondering is there any way to detect what kind of social locker which able to use this script. Honestly, I'm not familiar to WordPress platform.

If possible, could you tell me how this script work?

Thanks.

**Comment by baivong** [comment]
To detect Social Locker Plugins, I check the Global Variables in JavaScript and DOM Selectors.

Plugins in this script may be divided into 2 groups:

### Using JavaScript
They would hide, sometimes changing the DOM structure of the original content. Then replace it with the Social Widget. I find and recover content, then remove Widget.
Some Plugins constantly checking and re-insert Widget, I would override their Global Variables to prevent it.

### Using PHP
If they require only a Cookie is valid. I simply insert correct Cookie and reload this page.
If they need additional a valid Query, in the source code will contain Key or JavaScript Function to make an AJAX call. I find and run it to get original content.

**Comment by nntoan** [comment]
Thanks for your clarification, now I know how those bastard plugins work. Btw, there is a little problem with site https://dtv-ebook.com.

This script bypass that Social Locker successfully, but not in the first time. We have to reload the page to see the recovery content.

When you have spare time, please take a look into it.

Cheers.
